### ISSUE TITLE
Title

### ISSUE THREAD

**Issue by RB-Lab** [RB-Lab/wireknot-landing#5]
![title](https://cloud.githubusercontent.com/assets/5694678/12235801/583509d0-b876-11e5-9843-01a0e04b4d85.png)
Должен быть тем же, что и в первом заголовке

**Comment by Elena-panda** [comment]
![title](https://cloud.githubusercontent.com/assets/15869699/12613293/c60d57f6-c509-11e5-86ee-2c0149885389.png)
