### ISSUE TITLE
font size in e-mail field

### ISSUE THREAD

**Issue by RB-Lab** [RB-Lab/wireknot-landing#6]
![wtf](https://cloud.githubusercontent.com/assets/5694678/12235945/671d6e8c-b877-11e5-89d5-99f257db4de6.png)

**Comment by Elena-panda** [comment]
![wfman6b](https://cloud.githubusercontent.com/assets/15869699/12613503/3b630e78-c50b-11e5-93b4-5007319d3c62.png)

**Comment by RB-Lab** [comment]
placeholder
