### ISSUE TITLE
social buttons

### ISSUE THREAD

**Issue by RB-Lab** [RB-Lab/wireknot-landing#8]
съехали влево, промежуток потерялся
![social](https://cloud.githubusercontent.com/assets/5694678/12236155/761cce54-b878-11e5-8fd4-20d11f53a958.png)

**Comment by Elena-panda** [comment]
C этим разобралась!

![tf5qkce](https://cloud.githubusercontent.com/assets/15869699/12613240/705264fa-c509-11e5-8f82-a24710db4a02.png)
